### PR TITLE
removed release-it

### PR DESCRIPTION
**Pull request by leoromanovsky**
Fix vulnerabilities and remove un-used package.

```
➜  react-native-sdk git:(lr/upgrade-release) ✗ yarn why vm2
yarn why v1.22.19
[1/4] 🤔  Why do we have the module "vm2"...?
[2/4] 🚚  Initialising dependency graph...
[3/4] 🔍  Finding dependency...
error We couldn't find a match!
✨  Done in 0.25s.
```

### CODE REVIEW

**Comment by pavelflux** [comment]
@leoromanovsky I am not sure if major version upgrade won't break something. Did you check?

**Comment by leoromanovsky** [comment]
> @leoromanovsky I am not sure if major version upgrade won't break something, cause I have never worked with this package. Did you check?

@pavelflux I did not - however a code search shows me that this package is not currently being used. However I do like the functionality and would like to use it in the future.

Do you think we should instead remove it until we're ready to invest into the tool?

**Comment by pavelflux** [comment]
Hm? We do have a command in package json:

`"release": "release-it",` 

I tried running it, but it bumped the version of the SDK to 0.4.0 from 0.3.3, while I wanted just 0.3.4.
Did not find a way to specify version yet

**Comment by pavelflux** [comment]
@sameerank did you do the release manually here: https://github.com/Eppo-exp/react-native-sdk/releases/tag/v0.3.2 ?

**Review by sameerank — APPROVED** [review]

**Comment by sameerank** [comment]
> @sameerank did you do the release manually here: https://github.com/Eppo-exp/react-native-sdk/releases/tag/v0.3.2 ?

Yup, I cut that release. Actions did the publishing to npm though

https://github.com/Eppo-exp/react-native-sdk/actions/runs/6331017005

**Pull request merged**
